#!/bin/bash
if [ "$DISPLAY" == "" ]; then
	export DISPLAY=":0.0"
fi
CMD="which lxpanelctl >/dev/null 2>&1 && lxpanelctl alsastart >/dev/null"
if [ $(id -u) -eq 0 ]; then
        exec su $(who am i | cut -d' ' -f1) -c "$CMD"
else
        exec $CMD
fi
