#!/bin/bash
if [ "$DISPLAY" == "" ]; then
	export DISPLAY=":0.0"
fi
CMD="which lxpanelctl >/dev/null 2>&1 && lxpanelctl alsastop >/dev/null"
if [ $(id -u) -eq 0 ]; then
	exec su $(id -un) -c "$CMD"
else
	exec $CMD
fi
