#!/bin/bash

CMAKE_BUILD_TYPE=Release
CMAKE_TOOLCHAIN_FILE=/home/andreas/Code/Android/SDK/ndk/21.3.6528147/build/cmake/android.toolchain.cmake

ANDROID_ABI=armeabi-v7a
ANDROID_TOOLCHAIN=clang
ANDROID_ARM_NEON=ON
ANDROID_NATIVE_API_LEVEL=24
ANDROID_NO_UNDEFINED=OFF    # when "ON" show all undefined symbols as linker errors (standard value ist "ON")
                            # needed because mmal libs wouldn't build because of circular dependencies
ANDROID_SO_UNDEFINED=OFF    # when "ON" allow undefined symbols in shared libraries (standard value is "OFF")

DESTDIR=../build

mkdir -p temp
pushd temp
cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
-DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE \
-DANDROID_ABI=$ABI \
-DANDROID_TOOLCHAIN=$ANDROID_TOOLCHAIN \
-DANDROID_ARM_NEON=$ANDROID_ARM_NEON \
-DANDROID_NATIVE_API_LEVEL=$ANDROID_NATIVE_API_LEVEL \
-DANDROID_NO_UNDEFINED=$ANDROID_NO_UNDEFINED \
-DANDROID_SO_UNDEFINED=$ANDROID_SO_UNDEFINED \
../

make -j `nproc`
make -j `nproc` install DESTDIR=$DESTDIR

popd
