#!/bin/sh

# Setup GPIO and I2C ports for raspicam

# Broadcom GPIO numbers used here

# https://www.element14.com/community/docs/DOC-78141/l/identifying-your-model-of-raspberry-pi
rev=`cat /proc/cpuinfo | grep Revision | awk '{print $NF}'`
echo "setting GPIO for board revsion: $rev"

case $rev in

'0002'|'0003')
echo "B Rev1 - I2C 1 on GPIOs 2 & 3. GPIOs 5 & 27 for LED and power"
# i2c on these pins
gpio -g mode 0 in
gpio -g mode 0 alt0
gpio -g mode 1 in
gpio -g mode 1 alt0
#shutdown
gpio -g write 27 1
#LED
gpio -g write 5 1
;;

'0004'|'0005'|'0006'|'000d'|'000e'|'000f')
echo "B Rev2 - I2C 0 on GPIOs 0 & 1. GPIOs 5 & 21 for LED and power"
# i2c on these pins
gpio -g mode 0 in
gpio -g mode 0 alt0
gpio -g mode 1 in
gpio -g mode 1 alt0
#shutdown
gpio -g write 21 1
#LED
gpio -g write 5 1
;;

'0010'|'0012'|'0013'|'1041'|'a01041'|'a21041'|'900093')
echo "A+, B+, and B2 all revisions - I2C 0 on GPIOs 28 & 29. GPIOs 32 & 41 for LED and power"
# i2c can be on pins 0 and 1, so make sure they are not set to alt0
gpio -g mode 0 in
gpio -g mode 1 in
# i2c on these pins
gpio -g mode 28 in
gpio -g mode 28 alt0
gpio -g mode 29 in
gpio -g mode 29 alt0
#shutdown
gpio -g write 41 1
#LED
gpio -g write 32 1
;;

'a02082'|'a22082')
echo "Raspberry Pi3"
# https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=120702&start=100
# "Direct i2c1 to GPIO44&45."
# Pins 44&45 Alt1=i2c0, alt2=i2c1
# i2c0 can be on pins 0 and 1, so make sure they are not set to alt0
gpio -g mode 0 in
gpio -g mode 1 in
# i2c1 can be on pins 0 and 1, so make sure they are not set to alt0
gpio -g mode 2 in
gpio -g mode 3 in
gpio -g mode 28 in
gpio -g mode 29 in
# i2c on these pins
gpio -g mode 44 in
gpio -g mode 44 alt2
gpio -g mode 45 in
gpio -g mode 45 alt2
#shutdown
# you need this one: https://github.com/6by9/rpi3-gpiovirtbuf
#gpio -g write 41 1
./rpi3-gpiovirtbuf/rpi3-gpiovirtbuf s 133 1
#LED
#gpio -g write 32 1
i2cdetect -y 1
;;

*)
echo "Failed: don't know how to set GPIO for this board!"
;;
esac
