.TH vcgencmd 1 "January 2019" "Raspberry Pi vcgencmd" "User Commands"
.SH NAME
vcgencmd - send a command to the VideoCore
.SH SYNOPSIS
vcgencmd [-?] | [--help] | [-t] [COMMAND]
.SH DESCRIPTION
Send a command to the VideoCore and display the response.
.SH OPTIONS
.TP
.BR \-? ", " \-\-help\fR
Display basic usage information
.TP
.BR \-t\fR
Time how long it takes to return the result of a command
.TP
.BR commands \fR
Query the VideoCore to find out what commands it supports. Newer firmwares support more commands.
.TP
.BR "Exit status:"
 0   success
.br
-1   problem with VCHI
.br 
-2   VideoCore returned an error